name: "CI - DEV"

on:
    push:
        branches-ignore:
            - main

jobs:
    hello:
        name: "Hello world"
        runs-on: ubuntu-latest
        steps:
            - name: "step 1"
              run: echo "Hello world FROM Github Actions!"
            - name: "Failed step"
              # continue-on-error: true
              run: "bash -c 'exit 1'"
            - name: "notification"
              run: "echo Previous step failed"

    notify:
        name: "Notification center"
        runs-on: ubuntu-latest
        steps:
            - name: "Discord"
              run: "echo notify on discord"
