name: "CI - DEV"

on:
    push:
        branches-ignore:
            - main

jobs:
    hello:
        name: "Hello world"
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: "step 1"
              run: echo "Hello world FROM Github Actions!"
            - name: "Failed build step"
              # continue-on-error: true
              run: "bash -c 'exit 1'"
            - name: "unit tests"
              run: "echo Previous step failed"

    hello2:
        name: "Bonjour le monde"
        runs-on: ubuntu-latest
        steps:
            - name: "Dis bonjour"
              run: |
                  echo -n Bonjour
                  echo -n " "
                  echo "le monde"

    notify:
        needs: ["hello"]
        name: "Notification center"
        runs-on: ubuntu-latest
        steps:
            - name: "Discord"
              run: "echo notify on discord"
